package wizard

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type SetupWizard struct {
	dataPath	string
	reader		*bufio.Reader
}

func NewSetupWizard(dataPath string) *SetupWizard {
	return &SetupWizard{
		dataPath:	dataPath,
		reader:		bufio.NewReader(os.Stdin),
	}
}

func (w *SetupWizard) ShouldRun() bool {
	propsPath := filepath.Join(w.dataPath, "server.properties")
	_, err := os.Stat(propsPath)
	return os.IsNotExist(err)
}

func (w *SetupWizard) Run() error {
	fmt.Println()
	fmt.Println("╔════════════════════════════════════════════╗")
	fmt.Println("║       SCAXE-GO Setup Wizard                ║")
	fmt.Println("╚════════════════════════════════════════════╝")
	fmt.Println()
	fmt.Println("[*] Welcome to SCAXE-GO! This wizard will help you configure your server.")
	fmt.Println("[*] Press Enter to use default values shown in parentheses.")
	fmt.Println()

	fmt.Print("[?] Skip setup wizard and use defaults? (y/N): ")
	if strings.ToLower(w.getInput("n")) == "y" {
		return w.writeDefaults()
	}

	config := make(map[string]string)

	fmt.Print("[?] Server name (SCAXE Server): ")
	config["motd"] = w.getInput("SCAXE Server")

	for {
		fmt.Print("[?] Server port (19132): ")
		portStr := w.getInput("19132")
		port, err := strconv.Atoi(portStr)
		if err != nil || port <= 0 || port > 65535 {
			fmt.Println("[!] Invalid port. Please enter a number between 1-65535.")
			continue
		}
		config["server-port"] = portStr
		break
	}

	fmt.Print("[?] World name (world): ")
	config["level-name"] = w.getInput("world")

	fmt.Println("[*] Available generators: flat, normal, nether, ender")
	for {
		fmt.Print("[?] World generator (flat): ")
		gen := strings.ToLower(w.getInput("flat"))
		if gen == "flat" || gen == "normal" || gen == "nether" || gen == "ender" {
			config["level-type"] = strings.ToUpper(gen)
			break
		}
		fmt.Println("[!] Invalid generator. Choose: flat, normal, nether, ender")
	}

	fmt.Println("[*] Gamemodes: 0=Survival, 1=Creative, 2=Adventure, 3=Spectator")
	for {
		fmt.Print("[?] Default gamemode (0): ")
		gmStr := w.getInput("0")
		gm, err := strconv.Atoi(gmStr)
		if err != nil || gm < 0 || gm > 3 {
			fmt.Println("[!] Invalid gamemode. Enter 0-3.")
			continue
		}
		config["gamemode"] = gmStr
		break
	}

	for {
		fmt.Print("[?] Max players (20): ")
		mpStr := w.getInput("20")
		mp, err := strconv.Atoi(mpStr)
		if err != nil || mp <= 0 || mp > 1000 {
			fmt.Println("[!] Invalid number. Enter 1-1000.")
			continue
		}
		config["max-players"] = mpStr
		break
	}

	fmt.Print("[?] Enable PvP? (Y/n): ")
	if strings.ToLower(w.getInput("y")) == "n" {
		config["pvp"] = "false"
	} else {
		config["pvp"] = "true"
	}

	fmt.Println("[*] Difficulty: 0=Peaceful, 1=Easy, 2=Normal, 3=Hard")
	for {
		fmt.Print("[?] Difficulty (1): ")
		diffStr := w.getInput("1")
		diff, err := strconv.Atoi(diffStr)
		if err != nil || diff < 0 || diff > 3 {
			fmt.Println("[!] Invalid difficulty. Enter 0-3.")
			continue
		}
		config["difficulty"] = diffStr
		break
	}

	if err := w.writeConfig(config); err != nil {
		return err
	}

	fmt.Println()
	fmt.Println("[✓] Setup complete! Your server.properties has been created.")
	fmt.Println("[*] Starting server...")
	fmt.Println()

	return nil
}

func (w *SetupWizard) getInput(defaultVal string) string {
	input, _ := w.reader.ReadString('\n')
	input = strings.TrimSpace(input)
	if input == "" {
		return defaultVal
	}
	return input
}

func (w *SetupWizard) writeDefaults() error {
	config := map[string]string{
		"motd":		"SCAXE Server",
		"server-port":	"19132",
		"level-name":	"world",
		"level-type":	"FLAT",
		"gamemode":	"0",
		"max-players":	"20",
		"pvp":		"true",
		"difficulty":	"1",
	}
	return w.writeConfig(config)
}

func (w *SetupWizard) writeConfig(config map[string]string) error {

	if err := os.MkdirAll(w.dataPath, 0755); err != nil {
		return err
	}

	propsPath := filepath.Join(w.dataPath, "server.properties")
	file, err := os.Create(propsPath)
	if err != nil {
		return err
	}
	defer file.Close()

	file.WriteString("# SCAXE-GO Server Properties\n")
	file.WriteString("# Generated by Setup Wizard\n\n")

	defaults := map[string]string{
		"motd":			"SCAXE Server",
		"server-port":		"19132",
		"level-name":		"world",
		"level-type":		"FLAT",
		"level-seed":		"",
		"gamemode":		"0",
		"force-gamemode":	"false",
		"max-players":		"20",
		"pvp":			"true",
		"difficulty":		"1",
		"white-list":		"false",
		"spawn-protection":	"16",
		"view-distance":	"10",
		"online-mode":		"false",
	}

	for k, v := range config {
		defaults[k] = v
	}

	for k, v := range defaults {
		file.WriteString(fmt.Sprintf("%s=%s\n", k, v))
	}

	return nil
}
